services:
  - type: web
    name: chat-frontend
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_USER_SERVICE_URL
        value: https://chat-user-service.onrender.com
      - key: NEXT_PUBLIC_CHAT_SERVICE_URL
        value: https://chat-chat-service.onrender.com
      - key: NEXT_PUBLIC_MAIL_SERVICE_URL
        value: https://chat-mail-service.onrender.com